In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_json('fake_property_data.json')

In [7]:
df.insert(0, "property_id", range(1, len(df) + 1))

In [8]:
df.head()

,property_id,Property_Title,Address,Reviewed_Status,Most_Recent_Status,Source,Market,Occupancy,Flood,Street_Address,...,Longitude,Subdivision,Taxes,Selling_Reason,Seller_Retained_Broker,Final_Reviewer,School_Average,Valuation,HOA,Rehab
0,1,"875 Davis Overpass Suite 394, South Kathrynsid...","875 Davis Overpass Suite 394, South Kathrynsid...",,Closed,Internal,Chicago,None,None,875 Davis Overpass Suite 394,...,-81.853842,Manors,6389,Downsizing,None,Jason Miller,9.09,"[{'List_Price': 93528, 'Previous_Rent': 1699, ...","[{'HOA': 460, 'HOA_Flag': 'No'}, {'HOA': 476, ...","[{'Underwriting_Rehab': 66402, 'Rehab_Calculat..."
1,2,"1159 Johnson Pass Apt. 567, South Jamesfurt, M...","1159 Johnson Pass Apt. 567, South Jamesfurt, M...",Reviewed,Cancelled,Auction.com,Dallas,None,Minimal Flood,1159 Johnson Pass Apt. 567,...,-105.265714,Cliff,9321,None,None,Luis Garcia,7.71,"[{'List_Price': 434027, 'Previous_Rent': 2955,...","[{'HOA': 322, 'HOA_Flag': 'Yes'}, {'HOA': 219,...","[{'Underwriting_Rehab': 57763, 'Rehab_Calculat..."
2,3,"9082 Anna Villages Apt. 511, Port Juanshire, V...","9082 Anna Villages Apt. 511, Port Juanshire, V...",Null,Null,Opendoor,Tampa,No,Flood Zone,9082 Anna Villages Apt. 511,...,-77.250254,Square,9963,None,None,Samantha Pierce,6.04,"[{'List_Price': 353402, 'Previous_Rent': 3478}...","[{'HOA': 242, 'HOA_Flag': 'Yes'}, {'HOA': 470,...","[{'Underwriting_Rehab': 74265, 'Rehab_Calculat..."
3,4,"86578 Lawson Park Suite 865, South Brianfurt, ...","86578 Lawson Park Suite 865, South Brianfurt, ...",Closed,Cancelled,M.L.S.,,None,Flood Zone,86578 Lawson Park Suite 865,...,-85.460902,Springs,2173,Job Transfer,None,Samantha Pierce,3.44,"[{'List_Price': 149122, 'Previous_Rent': 3012,...","[{'HOA': 500, 'HOA_Flag': 'Yes'}]","[{'Underwriting_Rehab': 9019, 'Rehab_Calculati..."
4,5,"309 Roy Brook Apt. 282, Lake Scott, FL 84478","309 Roy Brook Apt. 282, Lake Scott, FL 84478",Closed,Cancelled,M.L.S.,Tampa,No,Flood Zone,309 Roy Brook Apt. 282,...,-82.300397,Brooks,5985,Investor Sale,Yes,Priya Sharma,9.01,"[{'List_Price': 362688, 'Previous_Rent': 2315,...","[{'HOA': 197, 'HOA_Flag': 'Yes'}, {'HOA': 424,...","[{'Underwriting_Rehab': 77074, 'Rehab_Calculat..."

In [9]:
print(df['Reviewed_Status'].value_counts())
print(df['Reviewed_Status'].dtype)

Reviewed_Status
 Closed           1059
Neww              1040
New               1009
Cancelled         1004
Accepted Offer    1003
                   996
Reviewed           995
Offered            980
Closed             970
Null               944
Name: count, dtype: int64
object

In [10]:
df['Reviewed_Status'] = df['Reviewed_Status'].str.strip()
df['Reviewed_Status'].replace('Neww', 'New', inplace=True)
df['Reviewed_Status'].replace('', np.nan, inplace=True)

C:\Users\developer\AppData\Local\Temp\ipykernel_18680\3372140612.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Reviewed_Status'].replace('Neww', 'New', inplace=True)
C:\Users\developer\AppData\Local\Temp\ipykernel_18680\3372140612.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Reviewed_Status'].replace('', np.nan, inplace=True)

In [11]:
df['Reviewed_Status'].isna().sum()

np.int64(996)

In [12]:
print(df['Most_Recent_Status'].value_counts())
print(df['Most_Recent_Status'].dtype)

Most_Recent_Status
Null           888
Pending        867
Pend           861
Cancel         840
Always Kick    839
               833
Available      831
Close          829
Closed         826
Cancelled      810
 Close         790
Kick           786
Name: count, dtype: int64
object

In [13]:
df['Most_Recent_Status'].isna().sum()

np.int64(0)

In [14]:
df['Most_Recent_Status'] = df['Most_Recent_Status'].str.strip()
df['Most_Recent_Status'].replace('Close', 'Closed', inplace=True)
df['Most_Recent_Status'].replace('pending', 'Pending', inplace=True)
df['Most_Recent_Status'].replace('Always Kick', 'Kick', inplace=True)
df['Most_Recent_Status'].replace('', np.nan, inplace=True)

C:\Users\developer\AppData\Local\Temp\ipykernel_18680\4265363577.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Most_Recent_Status'].replace('Close', 'Closed', inplace=True)
C:\Users\developer\AppData\Local\Temp\ipykernel_18680\4265363577.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Most_Recent_Status'].replace('pending', 'Pending', inplace=True)
C:\Users\developer\AppData\Local\Temp\ipykernel_18680\4265363577.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Most_Recent_Status'].replace('Always Kick', 'Kick', inplace=True)
C:\Users\developer\AppData\Local\Temp\ipykernel_18680\4265363577.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Most_Recent_Status'].replace('', np.nan, inplace=True)

In [15]:
print(df['Source'].value_counts())
print(df['Source'].dtype)

Source
M L S          1275
Opendoor       1274
Bulk           1272
Internal       1263
Auction.com    1247
M.L.S.         1240
 MLS           1236
Broker         1193
Name: count, dtype: int64
object

In [16]:
df['Source'] = df['Source'].str.strip()
df['Source'].replace(['M L S', 'M.L.S.'], 'MLS', inplace=True)

C:\Users\developer\AppData\Local\Temp\ipykernel_18680\2928016363.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Source'].replace(['M L S', 'M.L.S.'], 'MLS', inplace=True)

In [17]:
df['Source'].isna().sum()

np.int64(0)

In [18]:
print(df['Market'].value_counts())
print(df['Market'].dtype)

Market
Chicgo     1288
Chicago    1277
Atlanta    1261
Florida    1254
           1245
Tampa      1229
Dallas     1226
Dalas      1220
Name: count, dtype: int64
object

In [19]:
df['Market'] = df['Market'].str.strip()
df['Market'].replace('Chicgo', 'Chicago', inplace=True)
df['Market'].replace('Dalas', 'Dallas', inplace=True)
df['Market'].replace('', np.nan, inplace=True)

C:\Users\developer\AppData\Local\Temp\ipykernel_18680\2584312785.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Market'].replace('Chicgo', 'Chicago', inplace=True)
C:\Users\developer\AppData\Local\Temp\ipykernel_18680\2584312785.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Market'].replace('Dalas', 'Dallas', inplace=True)
C:\Users\developer\AppData\Local\Temp\ipykernel_18680\2584312785.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Market'].replace('', np.nan, inplace=True)

In [20]:
df['Market'].isna().sum()

np.int64(1245)

In [21]:
print(df['Occupancy'].value_counts())          
print(df['Occupancy'].dtype)

Occupancy
Yes    3424
No     3294
Name: count, dtype: int64
object

In [22]:
df['Occupancy'].isna().sum()

np.int64(3282)

In [23]:
print(df['Flood'].value_counts())          
print(df['Flood'].dtype)

Flood
Minimal Flood    3316
Flood Zone       3275
Name: count, dtype: int64
object

In [24]:
df['Flood'].isna().sum()

np.int64(3409)

In [25]:
print(df['Valuation'])

0       [{'List_Price': 93528, 'Previous_Rent': 1699, ...
1       [{'List_Price': 434027, 'Previous_Rent': 2955,...
2       [{'List_Price': 353402, 'Previous_Rent': 3478}...
3       [{'List_Price': 149122, 'Previous_Rent': 3012,...
4       [{'List_Price': 362688, 'Previous_Rent': 2315,...
                              ...
9995    [{'List_Price': 408947, 'High_FMR': 5480}, {'L...
9996    [{'List_Price': 183622, 'Previous_Rent': 1938,...
9997    [{'List_Price': 477121, 'Zestimate': 215341, '...
9998    [{'List_Price': 137917, 'Previous_Rent': 2079,...
9999                                                   []
Name: Valuation, Length: 10000, dtype: object

In [26]:
records_val = []
for id, val_list in df[['property_id', 'Valuation']].itertuples(index=False):         
    if isinstance(val_list, list):
        for d in val_list:   
            records_val.append({'property_id': id, **d})            
    

df_valuation = pd.DataFrame(records_val)

# df.itertuples(index=False) returns each row as a tuple and if index = True then index bi return ho jaega tuple me
# **d for unpacking key-value pair

In [27]:
df_valuation.head()

,property_id,List_Price,Previous_Rent,ARV,Rent_Zestimate,Low_FMR,Redfin_Value,Zestimate,Expected_Rent,High_FMR
0,1,93528,1699.0,130693.0,2047.0,1251.0,379528.0,NaN,NaN,NaN
1,1,281162,NaN,NaN,NaN,1306.0,515319.0,522504.0,2671.0,1859.0
2,1,175119,2188.0,NaN,NaN,1612.0,NaN,NaN,1386.0,NaN
3,1,168323,NaN,NaN,NaN,NaN,NaN,192171.0,3138.0,5157.0
4,2,434027,2955.0,187554.0,3324.0,NaN,NaN,NaN,NaN,NaN

In [28]:
df['HOA']

0       [{'HOA': 460, 'HOA_Flag': 'No'}, {'HOA': 476, ...
1       [{'HOA': 322, 'HOA_Flag': 'Yes'}, {'HOA': 219,...
2       [{'HOA': 242, 'HOA_Flag': 'Yes'}, {'HOA': 470,...
3                       [{'HOA': 500, 'HOA_Flag': 'Yes'}]
4       [{'HOA': 197, 'HOA_Flag': 'Yes'}, {'HOA': 424,...
                              ...
9995                     [{'HOA': 417, 'HOA_Flag': 'No'}]
9996    [{'HOA': 103, 'HOA_Flag': 'No'}, {'HOA': 334, ...
9997                                                   []
9998    [{'HOA': 461, 'HOA_Flag': 'Yes'}, {'HOA': 469,...
9999    [{'HOA': 18, 'HOA_Flag': 'No'}, {'HOA': 170, '...
Name: HOA, Length: 10000, dtype: object

In [29]:
records_hoa = []
for i, hoa_list in df[['property_id', 'HOA']].itertuples(index=False): 
    if isinstance(hoa_list, list):
        for d in hoa_list:   
            records_hoa.append({'property_id': id, **d})

df_hoa = pd.DataFrame(records_hoa)

In [30]:
df_hoa.head()

   property_id  HOA HOA_Flag
0        10000  460       No
1        10000  476      Yes
2        10000  322      Yes
3        10000  219      Yes
4        10000  242      Yes

In [31]:
df['Rehab']

0       [{'Underwriting_Rehab': 66402, 'Rehab_Calculat...
1       [{'Underwriting_Rehab': 57763, 'Rehab_Calculat...
2       [{'Underwriting_Rehab': 74265, 'Rehab_Calculat...
3       [{'Underwriting_Rehab': 9019, 'Rehab_Calculati...
4       [{'Underwriting_Rehab': 77074, 'Rehab_Calculat...
                              ...
9995    [{'Underwriting_Rehab': 49365, 'Rehab_Calculat...
9996    [{'Underwriting_Rehab': 29448, 'Rehab_Calculat...
9997    [{'Underwriting_Rehab': 63941, 'Rehab_Calculat...
9998    [{'Underwriting_Rehab': 34520, 'Rehab_Calculat...
9999    [{'Underwriting_Rehab': 55645, 'Rehab_Calculat...
Name: Rehab, Length: 10000, dtype: object

In [32]:
records_rehab = []
for i, rehab_list in df[['property_id', 'Rehab']].itertuples(index=False): 
    if isinstance(rehab_list, list):
        for d in rehab_list:   
            records_rehab.append({'property_id': id, **d})

df_rehab = pd.DataFrame(records_rehab)

In [33]:
df_rehab.head()

,property_id,Underwriting_Rehab,Rehab_Calculation,Paint,Flooring_Flag,Foundation_Flag,Roof_Flag,HVAC_Flag,Kitchen_Flag,Bathroom_Flag,Appliances_Flag,Windows_Flag,Landscaping_Flag,Trashout_Flag
0,10000,66402,54602,None,No,Yes,None,None,None,None,No,Yes,None,No
1,10000,20995,67666,Yes,Yes,Yes,No,Yes,Yes,None,None,Yes,No,No
2,10000,64582,68022,No,None,Yes,Yes,Yes,No,Yes,None,None,Yes,No
3,10000,57763,30244,Yes,No,None,None,No,No,No,Yes,No,No,Yes
4,10000,74265,29580,None,Yes,None,No,No,No,No,Yes,No,Yes,None

In [34]:
df['Layout'].value_counts()

Layout
Ranch       2547
Split       2489
Colonial    2410
Name: count, dtype: int64

In [35]:
df['Rent_Restricted'].value_counts()

Rent_Restricted
No     3386
Yes    3315
Name: count, dtype: int64

In [36]:
df['Parking'].value_counts()

Parking
Street      2523
Garage      2517
Driveway    2471
Name: count, dtype: int64

In [37]:
df['BasementYesNo'].value_counts()

BasementYesNo
No     3382
Yes    3253
Name: count, dtype: int64

In [38]:
df['Water'].value_counts()

Water
City    3365
Well    3332
Name: count, dtype: int64

In [39]:
df['Sewage'].value_counts()

Sewage
City      3435
Septic    3313
Name: count, dtype: int64

In [40]:
df['SQFT_MU']

0       1110
1       1184
2       2492
3       2586
4       1200
        ...
9995    2558
9996    2177
9997    1079
9998     599
9999    1544
Name: SQFT_MU, Length: 10000, dtype: int64

In [41]:
for i in df.columns:
    if df[i].dtype == object:
        df[i].fillna('unknown', inplace=True)

C:\Users\developer\AppData\Local\Temp\ipykernel_18680\2290762803.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna('unknown', inplace=True)

In [42]:
df.shape

(10000, 46)

In [43]:
df.isna().sum()

property_id               0
Property_Title            0
Address                   0
Reviewed_Status           0
Most_Recent_Status        0
Source                    0
Market                    0
Occupancy                 0
Flood                     0
Street_Address            0
City                      0
State                     0
Zip                       0
Property_Type             0
Highway                   0
Train                     0
Tax_Rate                  0
SQFT_Basement             0
HTW                       0
Pool                      0
Commercial                0
Water                     0
Sewage                    0
Year_Built                0
SQFT_MU                   0
SQFT_Total                0
Parking                   0
Bed                       0
Bath                      0
BasementYesNo             0
Layout                    0
Net_Yield                 0
IRR                       0
Rent_Restricted           0
Neighborhood_Rating       0
Latitude                  0
Longitude                 0
Subdivision               0
Taxes                     0
Selling_Reason            0
Seller_Retained_Broker    0
Final_Reviewer            0
School_Average            0
Valuation                 0
HOA                       0
Rehab                     0
dtype: int64

In [44]:
bl = pd.read_excel('Field Config.xlsx')
bl

               Column Name Target Table
0           Property_Title     property
1                  Address     property
2          Reviewed_Status        Leads
3       Most_Recent_Status        Leads
4                   Source        Leads
..                     ...          ...
61          Selling_Reason        leads
62  Seller_Retained_Broker        leads
63                HOA_Flag          HOA
64          Final_Reviewer        leads
65          School_Average     property

[66 rows x 2 columns]

In [45]:
bl['Column Name'] = bl[bl['Column Name'].isin(df.columns)]['Column Name']

In [46]:
bl[~bl['Column Name'].isin(df.columns)]

   Column Name Target Table
34         NaN    Valuation
35         NaN    Valuation
36         NaN    Valuation
37         NaN    Valuation
38         NaN    Valuation
39         NaN    Valuation
40         NaN    Valuation
41         NaN    Valuation
43         NaN        Rehab
44         NaN        Rehab
45         NaN        Rehab
46         NaN        Rehab
47         NaN        Rehab
48         NaN        Rehab
49         NaN        Rehab
50         NaN        Rehab
51         NaN        Rehab
52         NaN        Rehab
53         NaN        Rehab
54         NaN        Rehab
55         NaN        Rehab
60         NaN    Valuation
63         NaN          HOA

In [47]:
bl = bl.dropna()

In [48]:
bl.shape

(43, 2)

In [49]:
bl['Target Table'].unique()

array(['property', 'Leads', 'HOA', 'Taxes', 'leads'], dtype=object)

In [50]:
bl.groupby('Target Table')['Column Name'].count()

Target Table
HOA          1
Leads        6
Taxes        1
leads        3
property    32
Name: Column Name, dtype: int64

In [51]:
property_col = bl[bl['Target Table'] == 'property']['Column Name']
df_property = df.loc[:, property_col]
df_property

,Property_Title,Address,Market,Flood,Street_Address,City,State,Zip,Property_Type,Highway,...,Bed,Bath,BasementYesNo,Layout,Rent_Restricted,Neighborhood_Rating,Latitude,Longitude,Subdivision,School_Average
0,"875 Davis Overpass Suite 394, South Kathrynsid...","875 Davis Overpass Suite 394, South Kathrynsid...",Chicago,unknown,875 Davis Overpass Suite 394,South Kathrynside,CO,35116,SFR,Far,...,2,3,unknown,Split,Yes,2,38.415818,-81.853842,Manors,9.09
1,"1159 Johnson Pass Apt. 567, South Jamesfurt, M...","1159 Johnson Pass Apt. 567, South Jamesfurt, M...",Dallas,Minimal Flood,1159 Johnson Pass Apt. 567,South Jamesfurt,MN,60391,Single Family Home,unknown,...,2,2,unknown,Colonial,Yes,3,35.329786,-105.265714,Cliff,7.71
2,"9082 Anna Villages Apt. 511, Port Juanshire, V...","9082 Anna Villages Apt. 511, Port Juanshire, V...",Tampa,Flood Zone,9082 Anna Villages Apt. 511,Port Juanshire,VI,22393,Townhouse,unknown,...,5,2,No,Ranch,unknown,3,36.793896,-77.250254,Square,6.04
3,"86578 Lawson Park Suite 865, South Brianfurt, ...","86578 Lawson Park Suite 865, South Brianfurt, ...",unknown,Flood Zone,86578 Lawson Park Suite 865,South Brianfurt,DC,90366,Duplex,Near,...,1,2,No,Ranch,unknown,3,35.456811,-85.460902,Springs,3.44
4,"309 Roy Brook Apt. 282, Lake Scott, FL 84478","309 Roy Brook Apt. 282, Lake Scott, FL 84478",Tampa,Flood Zone,309 Roy Brook Apt. 282,Lake Scott,FL,84478,Townhouse,Far,...,5,4,Yes,Split,Yes,2,41.066408,-82.300397,Brooks,9.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"139 Fisher Spur, North Brandon, WA 23114","139 Fisher Spur, North Brandon, WA 23114",Chicago,unknown,139 Fisher Spur,North Brandon,WA,23114,Single Family Home,unknown,...,4,4,Yes,Colonial,Yes,5,41.585551,-84.880198,Curve,3.08
9996,"275 Gutierrez Views, Lake Victoria, WY 63275","275 Gutierrez Views, Lake Victoria, WY 63275",Dallas,Flood Zone,275 Gutierrez Views,Lake Victoria,WY,63275,Duplex,Near,...,2,2,unknown,Colonial,No,4,34.402968,-112.249250,Field,9.88
9997,"341 Vanessa Harbor, North Melissa, CT 39313","341 Vanessa Harbor, North Melissa, CT 39313",Tampa,Flood Zone,341 Vanessa Harbor,North Melissa,CT,39313,Single Family Home,Far,...,2,3,No,Split,No,4,39.496975,-103.962353,Junction,7.74
9998,"78647 Brittany Village, North Ethanborough, NY...","78647 Brittany Village, North Ethanborough, NY...",Chicago,Minimal Flood,78647 Brittany Village,North Ethanborough,NY,21362,Single Family Home,Near,...,1,3,unknown,unknown,unknown,1,41.295438,-104.227932,Locks,6.62
9999,"5461 Nichols Throughway, East Crystalborough, ...","5461 Nichols Throughway, East Crystalborough, ...",Tampa,Flood Zone,5461 Nichols Throughway,East Crystalborough,UT,8497,Single Family Home,Far,...,4,1,No,Colonial,No,3,38.546763,-80.907870,Light,3.73

In [52]:
df_property.columns

Index(['Property_Title', 'Address', 'Market', 'Flood', 'Street_Address',
       'City', 'State', 'Zip', 'Property_Type', 'Highway', 'Train', 'Tax_Rate',
       'SQFT_Basement', 'HTW', 'Pool', 'Commercial', 'Water', 'Sewage',
       'Year_Built', 'SQFT_MU', 'SQFT_Total', 'Parking', 'Bed', 'Bath',
       'BasementYesNo', 'Layout', 'Rent_Restricted', 'Neighborhood_Rating',
       'Latitude', 'Longitude', 'Subdivision', 'School_Average'],
      dtype='object')

In [53]:
df_property = df_property.drop_duplicates()

In [55]:
lead_col = bl[bl['Target Table'] == 'leads']['Column Name']
df_lead = df.loc[:, lead_col]
df_lead

     Selling_Reason Seller_Retained_Broker   Final_Reviewer
0        Downsizing                unknown     Jason Miller
1           unknown                unknown      Luis Garcia
2           unknown                unknown  Samantha Pierce
3      Job Transfer                unknown  Samantha Pierce
4     Investor Sale                    Yes     Priya Sharma
...             ...                    ...              ...
9995        unknown                    Yes   David Thompson
9996        unknown                unknown  Sophia Williams
9997        unknown                    Yes     Jason Miller
9998  Investor Sale                     No  Samantha Pierce
9999     Downsizing                    Yes      Emily Patel

[10000 rows x 3 columns]

In [56]:
df_lead['Property_Title'] = df_property['Property_Title']

In [57]:
df_lead

,Selling_Reason,Seller_Retained_Broker,Final_Reviewer,Property_Title
0,Downsizing,unknown,Jason Miller,"875 Davis Overpass Suite 394, South Kathrynsid..."
1,unknown,unknown,Luis Garcia,"1159 Johnson Pass Apt. 567, South Jamesfurt, M..."
2,unknown,unknown,Samantha Pierce,"9082 Anna Villages Apt. 511, Port Juanshire, V..."
3,Job Transfer,unknown,Samantha Pierce,"86578 Lawson Park Suite 865, South Brianfurt, ..."
4,Investor Sale,Yes,Priya Sharma,"309 Roy Brook Apt. 282, Lake Scott, FL 84478"
...,...,...,...,...
9995,unknown,Yes,David Thompson,"139 Fisher Spur, North Brandon, WA 23114"
9996,unknown,unknown,Sophia Williams,"275 Gutierrez Views, Lake Victoria, WY 63275"
9997,unknown,Yes,Jason Miller,"341 Vanessa Harbor, North Melissa, CT 39313"
9998,Investor Sale,No,Samantha Pierce,"78647 Brittany Village, North Ethanborough, NY..."
9999,Downsizing,Yes,Emily Patel,"5461 Nichols Throughway, East Crystalborough, ..."

In [144]:
# hoa_col = bl[bl['Target Table'] == 'HOA']['Column Name']
# df_hoa = df.loc[:, hoa_col]
# df_hoa

In [58]:
tax_col = bl[bl['Target Table'] == 'Taxes']['Column Name']
df_tax = df.loc[:, tax_col]
df_tax

      Taxes
0      6389
1      9321
2      9963
3      2173
4      5985
...     ...
9995   4822
9996   4850
9997   8370
9998   9005
9999   5199

[10000 rows x 1 columns]

In [59]:
df_tax['Property_Title'] = df_property['Property_Title']
df_tax['Property_Type']  = df_property['Property_Type']   
df_tax['Tax_Rate'] = df['Tax_Rate']

In [60]:
df_tax

,Taxes,Property_Title,Property_Type,Tax_Rate
0,6389,"875 Davis Overpass Suite 394, South Kathrynsid...",SFR,2.95
1,9321,"1159 Johnson Pass Apt. 567, South Jamesfurt, M...",Single Family Home,1.75
2,9963,"9082 Anna Villages Apt. 511, Port Juanshire, V...",Townhouse,2.19
3,2173,"86578 Lawson Park Suite 865, South Brianfurt, ...",Duplex,3.39
4,5985,"309 Roy Brook Apt. 282, Lake Scott, FL 84478",Townhouse,2.20
...,...,...,...,...
9995,4822,"139 Fisher Spur, North Brandon, WA 23114",Single Family Home,3.34
9996,4850,"275 Gutierrez Views, Lake Victoria, WY 63275",Duplex,3.18
9997,8370,"341 Vanessa Harbor, North Melissa, CT 39313",Single Family Home,2.94
9998,9005,"78647 Brittany Village, North Ethanborough, NY...",Single Family Home,1.28
9999,5199,"5461 Nichols Throughway, East Crystalborough, ...",Single Family Home,3.39

In [1]:
from sqlalchemy import create_engine

In [2]:
db_connection_str = 'mysql+mysqldb://db_user:6equj5_db_user@localhost:3306/home_db'

In [3]:
db_connection = create_engine(db_connection_str)
db_connection

Engine(mysql+mysqldb://db_user:***@localhost:3306/home_db)

In [61]:
df_tax.to_sql('tax', db_connection, if_exists='replace', index=False)

10000

In [64]:
df_hoa.to_sql('hoa', db_connection, if_exists='replace', index=False)

9993

In [79]:
df_valuation.to_sql('valuation', db_connection, if_exists='replace', index=False)

24705

In [84]:
df_lead.to_sql('lead', db_connection, if_exists='replace', index=False)

10000

In [90]:
df_property.to_sql('properties', db_connection, if_exists='replace', index=False)

10000

In [77]:
for i in df_valuation.columns:
    if df_valuation[i].dtype == float:
        df_valuation[i].fillna(df_valuation[i].median(), inplace=True)

C:\Users\developer\AppData\Local\Temp\ipykernel_18680\88713061.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_valuation[i].fillna(df_valuation[i].median(), inplace=True)
C:\Users\developer\AppData\Local\Temp\ipykernel_18680\88713061.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_valuation[i].fillna(df_valuation[i].median(), inplace=True)
C:\Users\developer\AppData\Local\Temp\ipykernel_18680\88713061.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_valuation[i].fillna(df_valuation[i].median(), inplace=True)
C:\Users\developer\AppData\Local\Temp\ipykernel_18680\88713061.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_valuation[i].fillna(df_valuation[i].median(), inplace=True)
C:\Users\developer\AppData\Local\Temp\ipykernel_18680\88713061.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_valuation[i].fillna(df_valuation[i].median(), inplace=True)
C:\Users\developer\AppData\Local\Temp\ipykernel_18680\88713061.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_valuation[i].fillna(df_valuation[i].median(), inplace=True)
C:\Users\developer\AppData\Local\Temp\ipykernel_18680\88713061.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_valuation[i].fillna(df_valuation[i].median(), inplace=True)
C:\Users\developer\AppData\Local\Temp\ipykernel_18680\88713061.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_valuation[i].fillna(df_valuation[i].median(), inplace=True)